services:
  ui:
    build:
      context: ../..
      dockerfile: services/streamlit/Dockerfile
    container_name: rag-ui
    ports:
      - 8501:8501
    volumes:
      - ../../.env:/app/.env
      - ../../llm:/app/llm
      - ./requirements.txt:/app/requirements.txt
      - ../../.streamlit:/app/.streamlit
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_FILTERS=resource-migrator=warn deletion-marker-migrator=warn
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    restart: unless-stopped

  grafana-provisioner:
    build:
      context: ./provisioner
      dockerfile: Dockerfile
    container_name: grafana-provisioner
    depends_on:
      - grafana
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_USER=admin
      - GRAFANA_PASS=admin
    restart: "no"
    networks:
      - default
